version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: auto
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "@chainlink/contracts"
        versions: ["*"]
      - dependency-name: "@chainlink/contracts-ccip"
        versions: ["*"]
      - dependency-name: "@chainlink/local"
        versions: ["*"]
