name: Check external links

on:
  schedule:
    - cron: '59 23 * * */7'
  workflow_dispatch:

jobs:
  check-external-links:
    name: Check external links
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm i
      - name: Run external link checks
        run: npm run linkcheck-external
